INSERT INTO History(id, PLAYER_ONE, PLAYER_TWO, WINNER) VALUES(0, 'A', 'B', 'A');
INSERT INTO History(id, PLAYER_ONE, PLAYER_TWO, WINNER) VALUES(1, 'B', 'A', 'A');
INSERT INTO History(id, PLAYER_ONE, PLAYER_TWO, WINNER) VALUES(2, 'A', 'C', 'A');
INSERT INTO History(id, PLAYER_ONE, PLAYER_TWO, WINNER) VALUES(3, 'A', 'D', 'A');

INSERT INTO Leaderboard VALUES('A', 1);
INSERT INTO Leaderboard VALUES('B', 3);
